### ISSUE TITLE
Can't compile and run.

### ISSUE THREAD

**Issue by Oceania2018** [fsprojects/TensorFlow.FSharp#23]
Hi How can I make Tensorflow.FSharp run?
I can't find these packages below:
![image](https://user-images.githubusercontent.com/1705364/52824958-7f3a8700-3080-11e9-93b1-0348f30a0fd8.png)

**Comment by sir-deenicus** [comment]
In setup folder, there should be a setup.fsx file. You have to run it first in an F# interactive and it will generate what's needed.

**Comment by moloneymb** [comment]
@Oceania2018 Did running setup/setup.fsx manage to fix your issue?

**Comment by Oceania2018** [comment]
@moloneymb Havn't get it out.
![image](https://user-images.githubusercontent.com/1705364/52982020-2c770d00-33a9-11e9-8eff-0d5ae6568725.png)

**Comment by moloneymb** [comment]
You'll have to run setup via fsiAnyCpu (as per ReadMe.md). Alternatively you can select the code in setup.fsx and hit Alt-Enter to send the code to fsi. 

`fsiAnyCpu setup\setup.fsx`

**Comment by Oceania2018** [comment]
@moloneymb build successfully. Thanks.

**Comment by moloneymb** [comment]
No worries
