### ISSUE TITLE
A couple bugs related to Shape

### ISSUE THREAD

**Issue by sir-deenicus** [fsprojects/TensorFlow.FSharp#25]
Running `df (v 3.0) |> DT.Eval` (or similar) from [dsl-live.fsx](https://github.com/fsprojects/TensorFlow.FSharp/blob/master/examples/dsl-live.fsx#L40) results in an error: 

`Cannot compute the partial derivative for node 'BroadcastTo' as it's unreachable from the output node(s).`

As far as I can tell, this occurs only when evaluating scalar -> scalar derivatives. I've been able to narrow the error down to: https://github.com/fsprojects/TensorFlow.FSharp/blob/master/src/TensorFlow.FSharp/dsl.fs#L929

---

This [`tf { return (vec [1.0; 2.0]).[0..0] }`](https://github.com/fsprojects/TensorFlow.FSharp/blob/master/tests/dsl-tests.fsx#L48) no longer works as it returns a shape mismatch error. I guess maybe it's expecting a vector and is receiving a scalar?

---

Also, a question, it seems like tensor4 and tensor3 require that all dimensions are equal, is that correct?

Thanks

**Comment by dsyme** [comment]
Thanks, will check all these.  Even more motivation to add systematic testing

> Running `df (v 3.0) |> DT.Eval` (or similar) from [dsl-live.fsx](https://github.com/fsprojects/TensorFlow.FSharp/blob/master/examples/dsl-live.fsx#L40) results in an error:

Looks like we need to eliminate a BroadcastTo (which is likely scalar -> scalar)

> This [`tf { return (vec [1.0; 2.0]).[0..0] }`](https://github.com/fsprojects/TensorFlow.FSharp/blob/master/tests/dsl-tests.fsx#L48) no longer works as it returns a shape mismatch error. I guess maybe it's expecting a vector and is receiving a scalar?

This sounds like a bug from the recent rewrite of the indexing logic

> This [`tf { return (vec [1.0; 2.0]).[0..0] }`](https://github.com/fsprojects/TensorFlow.FSharp/blob/master/tests/dsl-tests.fsx#L48) no longer works as it returns a shape mismatch error. I guess maybe it's expecting a vector and is receiving a scalar?

That sounds like a bug.

**Comment by dsyme** [comment]
Thanks for reporting this, I've fixed the issues and added basic set of tests
