### ISSUE TITLE
Instructions to build livecheck tooling seem to be out-of-date

### ISSUE THREAD

**Issue by fwaris** [fsprojects/TensorFlow.FSharp#30]
I get the following error when trying to build livecheck tooling using the supplied instructions:

git clone http://github.com/Microsoft/visualfsharp
cd visualfsharp
git fetch https://github.com/dsyme/visualfsharp livecheck  
git checkout livecheck **_<--- error: pathspec 'livecheck' did not match any file(s) known to git..\build.cmd vs_**
cd ..

**Comment by moloneymb** [comment]
Thanks for bringing this to our attention. I'll have some time to look at it this week and get back to you.

**Comment by moloneymb** [comment]
Try adding a remote

git clone http://github.com/Microsoft/visualfsharp
cd visualfsharp
git remote add dsyme  https://github.com/dsyme/visualfsharp
git checkout livecheck
cd ..
